export const productGalleryStyles = {
  rootStack: {
    spacing: 2,
  },
  mainFrame: (frame: string) => ({
    position: "relative",
    borderRadius: 2,
    p: 0,
    bgcolor: "#f5efe7",
    width: "100%",
    aspectRatio: { xs: "4 / 3", md: "16 / 10" },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: "0 16px 30px rgba(55,67,115,0.15)",
    "&::before": {
      content: '""',
      pointerEvents: "none",
      position: "absolute",
      inset: 0,
      backgroundImage: `url("data:image/svg+xml,${frame}")`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "100% 100%",
      opacity: 1,
      zIndex: 2,
    },
  }),
  mainImage: (hasImage: boolean, isZoomed: boolean) => ({
    width: hasImage
      ? { xs: "90%", sm: "70%", md: "60%" }
      : { xs: 140, sm: 160, md: 180 },
    height: hasImage ? "94%" : { xs: 140, sm: 160, md: 180 },
    position: "relative",
    zIndex: 0,
    cursor: hasImage ? (isZoomed ? "zoom-out" : "zoom-in") : "default",
    "&:focus-visible": {
      outline: "2px solid rgba(55,67,115,0.8)",
      outlineOffset: 2,
    },
  }),
  mainImageElement: (
    hasImage: boolean,
    isZoomed: boolean,
    zoomOrigin: string,
  ) => ({
    objectFit: "contain" as const,
    opacity: hasImage ? 0.98 : 0.85,
    transform: isZoomed ? "scale(1.9)" : "scale(1)",
    transformOrigin: zoomOrigin,
    transition: "transform 180ms ease",
    willChange: "transform",
  }),
  thumbsGrid: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: { xs: 1.5, sm: 2 },
  },
  thumbsViewport: {
    width: "100%",
    position: "relative",
    overflow: "visible",
  },
  thumbsNavButton: (side: "left" | "right") => ({
    position: "absolute",
    top: "50%",
    transform: "translateY(-50%)",
    zIndex: 3,
    [side]: { xs: 8, sm: 12, md: -18 },
    border: "1px solid",
    borderColor: "rgba(55,67,115,0.18)",
    backgroundColor: "rgba(255,255,255,0.64)",
    backdropFilter: "blur(2px)",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.88)",
    },
  }),
  thumbsMetaStack: {
    alignItems: "center",
    mt: 1.5,
  },
  thumbsCounter: {
    mt: 0.25,
    fontWeight: 700,
    color: "primary.main",
    minWidth: 52,
    textAlign: "center",
  },
  thumbsDotsRow: {
    justifyContent: "center",
  },
  thumbsDot: (active: boolean) => ({
    width: active ? 18 : 8,
    height: 8,
    borderRadius: 999,
    backgroundColor: active ? "primary.main" : "rgba(55,67,115,0.25)",
    transition: "all 150ms ease",
  }),
  thumbButton: (isActive: boolean, thumbFrame: string) => ({
    position: "relative",
    cursor: "pointer",
    borderRadius: 1,
    border: "none",
    p: 0,
    bgcolor: "#f5efe7",
    width: "100%",
    height: { xs: 136, sm: 152 },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: isActive
      ? "0 16px 30px rgba(240,157,133,0.32)"
      : "0 10px 20px rgba(55,67,115,0.15)",
    transition: "transform 180ms ease, box-shadow 180ms ease",
    "&:hover": { transform: "translateY(-2px)" },
    "&::before": {
      content: '""',
      pointerEvents: "none",
      position: "absolute",
      inset: 0,
      backgroundImage: `url("data:image/svg+xml,${thumbFrame}")`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "100% 100%",
      opacity: isActive ? 1 : 0.9,
      zIndex: 2,
    },
  }),
  thumbImage: (thumbHasImage: boolean) => ({
    width: thumbHasImage ? "78%" : { xs: 58, sm: 66 },
    height: thumbHasImage ? "90%" : { xs: 58, sm: 66 },
    position: "relative",
    zIndex: 0,
  }),
  thumbImageElement: (thumbHasImage: boolean) => ({
    objectFit: "contain" as const,
    opacity: thumbHasImage ? 0.98 : 0.85,
  }),
} as const;
