export const productCardStyles = {
  root: (tiltDeg: number, frame: string, frameInset: number) => ({
    position: "relative",
    borderRadius: 3,
    background: "#f5efe7",
    overflow: "hidden",
    boxShadow: "0 10px 24px rgba(0,0,0,0.12)",
    transform: { xs: "none", md: `rotate(${tiltDeg}deg)` },
    transition: "transform 220ms ease, box-shadow 220ms ease",
    "&:hover": {
      transform: { xs: "none", md: "rotate(0deg) translateY(-6px)" },
      boxShadow: "0 16px 30px rgba(0,0,0,0.16)",
    },
    aspectRatio: "300 / 220",
    "&::before": {
      content: '""',
      pointerEvents: "none",
      position: "absolute",
      inset: frameInset,
      backgroundImage: `url("data:image/svg+xml,${frame}")`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "100% 100%",
      zIndex: 0,
    },
  }),
  cardLinkOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 1,
    borderRadius: 3,
    "&:focus-visible": {
      outline: "2px solid rgba(55,67,115,0.8)",
      outlineOffset: 2,
    },
  },
  contentStack: (safePadding: number) => ({
    position: "relative",
    zIndex: 2,
    height: "100%",
    p: `${safePadding}px`,
    justifyContent: "center",
    gap: 3,
    pointerEvents: "none",
  }),
  titleRow: {
    direction: "row",
    justifyContent: "center",
    alignItems: "flex-start",
    gap: 2,
    flexWrap: "wrap",
  },
  badgesRow: {
    alignItems: "center",
    justifyContent: "center",
    flexWrap: "wrap",
    rowGap: 0.75,
  },
  title: {
    fontSize: 18,
    fontWeight: 900,
    lineHeight: 1.1,
    letterSpacing: 0.2,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  badgeChip: (badge: "FREE" | "TOP") => ({
    fontWeight: 900,
    letterSpacing: 0.6,
    borderRadius: 2,
    height: 24,
    mt: 0.25,
    background:
      badge === "FREE" ? "rgba(60,150,140,0.16)" : "rgba(240,160,80,0.18)",
  }),
  footerRow: {
    direction: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 2,
  },
  price: {
    fontWeight: 900,
    fontSize: 20,
  },
  levelChip: {
    fontWeight: 900,
    fontSize: 12,
    letterSpacing: 0.5,
    borderRadius: 2,
    height: 24,
    mt: 0.25,
    backgroundColor: "#F5EDE9",
    color: "primary.main",
  },
  ctaButton: {
    px: 2.9,
    minWidth: 120,
    pointerEvents: "auto",
  },
} as const;
