export const productGalleryStyles = {
  rootStack: {
    spacing: 2,
  },
  mainFrame: (frame: string) => ({
    position: "relative",
    borderRadius: 2,
    p: 0,
    bgcolor: "#f5efe7",
    width: "100%",
    aspectRatio: { xs: "4 / 3", md: "16 / 10" },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: "0 16px 30px rgba(55,67,115,0.15)",
    "&::before": {
      content: '""',
      pointerEvents: "none",
      position: "absolute",
      inset: 0,
      backgroundImage: `url("data:image/svg+xml,${frame}")`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "100% 100%",
      opacity: 1,
      zIndex: 2,
    },
  }),
  mainImage: (hasImage: boolean) => ({
    width: hasImage ? { xs: "90%", sm: "70%", md: "60%" } : { xs: 140, md: 180 },
    height: hasImage ? "94%" : { xs: 140, md: 180 },
    objectFit: "contain",
    opacity: hasImage ? 0.98 : 0.85,
    position: "relative",
    zIndex: 0,
  }),
  thumbsGrid: {
    width: "100%",
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: { xs: 1.5, sm: 2 },
  },
  thumbButton: (isActive: boolean, thumbFrame: string) => ({
    position: "relative",
    cursor: "pointer",
    borderRadius: 1,
    border: "none",
    p: 0,
    bgcolor: "#f5efe7",
    width: "100%",
    height: { xs: 136, sm: 152 },
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    boxShadow: isActive
      ? "0 16px 30px rgba(240,157,133,0.32)"
      : "0 10px 20px rgba(55,67,115,0.15)",
    transition: "transform 180ms ease, box-shadow 180ms ease",
    "&:hover": { transform: "translateY(-2px)" },
    "&::before": {
      content: '""',
      pointerEvents: "none",
      position: "absolute",
      inset: 0,
      backgroundImage: `url("data:image/svg+xml,${thumbFrame}")`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "100% 100%",
      opacity: isActive ? 1 : 0.9,
      zIndex: 2,
    },
  }),
  thumbImage: (thumbHasImage: boolean) => ({
    width: thumbHasImage ? "78%" : { xs: 58, sm: 66 },
    height: thumbHasImage ? "90%" : { xs: 58, sm: 66 },
    objectFit: "contain",
    opacity: thumbHasImage ? 0.98 : 0.85,
    position: "relative",
    zIndex: 0,
  }),
} as const;
