export const stickerFieldStyles = {
  root: {
    display: "grid",
    gap: 1,
  },
  frameBox: (multiline: boolean, frame: string) => ({
    position: "relative",
    background: "#f5efe7",
    borderRadius: 2,
    boxShadow: "0 10px 24px rgba(0,0,0,0.12)",
    overflow: "hidden",
    aspectRatio: multiline ? "1200 / 280" : "1200 / 110",
    "&::before": {
      content: '""',
      pointerEvents: "none",
      position: "absolute",
      inset: 0.5,
      backgroundImage: `url("data:image/svg+xml,${frame}")`,
      backgroundRepeat: "no-repeat",
      backgroundSize: "100% 100%",
      backgroundPosition: "center",
      transform: "translateX(-3px)",
      zIndex: 0,
    },
  }),
  inputWrap: (multiline: boolean) => ({
    position: "absolute",
    inset: 0,
    zIndex: 1,
    display: "flex",
    alignItems: multiline ? "stretch" : "center",
    px: 5,
    pt: multiline ? 5 : 0,
    pb: multiline ? 3 : 0,
  }),
  inputBase: {
    width: "100%",
    fontWeight: 700,
    fontSize: 18,
    color: "rgba(18,28,56,0.95)",
    "& textarea": {
      lineHeight: 1.6,
      resize: "none",
      paddingTop: "38px",
      boxSizing: "border-box",
    },
    "& input::placeholder, & textarea::placeholder": {
      color: "rgba(18,28,56,0.45)",
      fontWeight: 700,
      opacity: 1,
    },
  },
  errorText: (hasError: boolean) => ({
    fontSize: 13,
    lineHeight: 1.3,
    fontWeight: 700,
    color: "#c24b4b",
    pl: 1,
    minHeight: "1.1em",
    visibility: hasError ? "visible" : "hidden",
  }),
} as const;
